swagger: "2.0"
info:
  version: "0.0.1"
  title: "Node Js Projects"
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /api/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /info:
    # binds a127 app logic to a route
    x-swagger-router-controller: nodeController
    get:
      description: Returns a array of infos
      # used as the method name of the controller
      operationId: getInfo
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/InfoResponse"
            # a pointer to a definition
            # $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Returns a array of infos
      # used as the method name of the controller
      operationId: createInfo
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/InfoResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /info/{infoId}:
    # binds a127 app logic to a route
    x-swagger-router-controller: nodeController
    get:
      description: Returns an info
      # used as the method name of the controller
      operationId: getInfoById
      parameters:
        - in: path
          name: infoId   # Note the name is the same as in the path
          required: true
          type: string
          minimum: 1
          description: The info ID.
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/InfoResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Update an info
      # used as the method name of the controller
      operationId: updateInfo
      parameters:
        - in: path
          name: infoId   # Note the name is the same as in the path
          required: true
          type: string
          minimum: 1
          description: The info ID.
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/InfoResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Delete an info
      # used as the method name of the controller
      operationId: deleteInfo
      parameters:
        - in: path
          name: infoId   # Note the name is the same as in the path
          required: true
          type: string
          minimum: 1
          description: The info ID.
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/InfoResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  InfoResponse:
    required:
      - id
      - name
    properties:
      id:
        type: integer
      name:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
